### ISSUE TITLE
Data.Record.Builder.modify

### ISSUE THREAD

**Issue by joneshf** [purescript/purescript-record#16]
Asked on slack, but figure it is less likely to get lost here.

I noticed there's no `modify` for `Data.Record.Builder` (akin to `modify` in `Data.Record`). Was that an intentional choice or an oversight? If an oversight, I'll submit a PR.

It might also be possible if there were a `Functor` instance for `Builder`. Would this work without breaking things? I remember we talked about adding a `Profunctor` instance, but it would break something. So, `Functor` is the next best thing, I think.

**Comment by garyb** [comment]
I would have thought it's an oversight :)

**Comment by paf31** [comment]
A `Functor` instance would definitely not be possible, since it would allow non-linear uses of the input argument to sneak in. Same for `Profunctor`.

I think `modify` is safe though.
