### ISSUE TITLE
Add map, traverse etc.

### ISSUE THREAD

**Issue by paf31** [purescript/purescript-record#19]
cc @justinwoo @joneshf

I think it would be interesting to add these for `Homogeneous` records, once we merge `Type.Row.Homogeneous`.

**Comment by paulyoung** [comment]
This was merged and released https://github.com/purescript/purescript-typelevel-prelude/pull/20.

**Comment by paulyoung** [comment]
FYI @natefaubion, since you and I have discussed having `sequence` for records.

**Comment by paf31** [comment]
We've discussed this before, and I think it belongs in a separate repo. The reason is that there is not just one sensible definition of `map` for records, and `Homogeneous` could be the basis of a `newtype` and an associated list of instances.
