### ISSUE TITLE
Alternative `build` for building a record from scratch

### ISSUE THREAD

**Issue by kl0tl** [purescript/purescript-record#52]
Hi everyone! 👋

Would anyone be opposed to a `build' :: Builder {} { | row } -> { | row }` function to build a record from scratch? The implementation is only `flip build $ {}` but it’s a convenient little function to compose in some pointfree scenarios.

**Comment by hdgarrood** [comment]
I think this is probably justifiable, although I'd suggest calling it `buildFromScratch` or something instead;  think primes are best avoided in library APIs.
