### ISSUE TITLE
Add new and run to Record.ST

### ISSUE THREAD

**Issue by kl0tl** [purescript/purescript-record#68]
Foreign.Object.ST and Data.Array.ST export means of creating empty mutable structures without having to thaw an immutable one. Should we also export `new :: forall h. ST h (STRecord h ())` from Record.ST for consistency?

There’s also Foreign.Object.runST and Data.Array.ST.run to avoid copying the mutable structure in the end. Any reason not to add a similar `run :: forall r. (forall h. ST h (STRecord h r)) -> Record r` to Record.ST? This would require an `unsafeFreeze :: forall h r. STRecord h r -> ST h (Record r)` function that we could export with an `unsafeThaw :: forall h r. Record r -> ST h (STRecord h r)` function from a new Record.ST.Unsafe module.

**Comment by MonoidMusician** [comment]
Do you mean `new :: forall h. ST h (STRecord h ())` (with an empty row)?

**Comment by kl0tl** [comment]
Oh yes, sorry about that, I wrote `ST h (STRecord h r)` too many times to notice anymore 🙃
